version: "3"
services:
  mysql:
    image: "mysql:5.7"
    ports:
      - 3306:3306
    volumes:
      - ./data/mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=toor
      - MYSQL_DATABASE=main
  redis:
    image: "redis:3-alpine"
    ports:
      - 6379:6379
